### ISSUE TITLE
Relax `psr/log` requirement

### ISSUE THREAD

**Issue by zaporylie** [Target365/sdk-for-php#11]
https://github.com/Target365/sdk-for-php/blob/880dbfce3cd16a4af7eca53c976c47e24fd121aa/composer.json#L10

Drupal 10 requires [psr/log:^3.0](https://git.drupalcode.org/project/drupal/-/blob/10.1.x/core/composer.json#L44) which is in conflict with the requirement for this package. Any chance the requirement could be relaxed to support other versions of psr/log?

**Comment by HansOlavS** [comment]
Thanks for the PR, @zaporylie. I'm merging it now.
