### ISSUE TITLE
Duplicate setSmscTransactionId method in DeliveryReport

### ISSUE THREAD

**Issue by eivols** [Target365/sdk-for-php#13]
https://github.com/Target365/sdk-for-php/blob/master/src/Model/DeliveryReport.php

See line 236 and 247. Line 247 should be setSmscStatus()

**Comment by HansOlavS** [comment]
Thanks, @eivols! Will fix ASAP.

**Comment by HansOlavS** [comment]
Fixed in v1.8.13
